#Name of NEUT card file needed by T2KRW
neutcard = "/user/sjenkins/neut.d.card"

#List of HighLand files to process
filelist = ["filelist.txt"]

#Maximum number of events to process from the TChain.
#Comment out or set to a negative number to read all events.
#max_events = 10000

#Name to use for the output file
#The file name will be name + FD name (in generate list) + .root
output_prefix = "FDS_"


#List of fake data studies to generate weights for. These strings
#must match the names used in the TOML table below.
generate = [
#	"SPPAdv",
#	"RStoMartini",
#	"HadronAlt",
	"RSDelta"
]

#Each fake data study is defined as a sub-table entry in the FDS table.
#The name after "FDS." is a user defined name and the one
#needed above.

#The impl_name is an array of the dial names as defined by T2KRW.
#For generating fake data studies, dial values are required
#The values array is for setting the dial values by hand, as an array
#of floating point numbers


[FDS.SPPAdv]
impl_name = ["SPPTwk_LowPpi2020"]
values = [ [0.77, 1.0] ]

[FDS.RStoMartini]
impl_name = ["RS_toMartiniTwkDial"]
values = [ [0.0, 1.0] ]

[FDS.HadronAlt]
impl_name = ["ROM3M3", "ROM1M1", "ROM1M3"]
values = [ [1.9, 0.1], [0.1, 1.9], [0.1, 1.9] ]

[FDS.RSDelta]
impl_name = ["MDLSPiEj"]
values = [[0.0, 1.0]]
